services:
  db:
    image: postgres:16-alpine
    container_name: coes_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432" # HOST EXTERN:INTERN
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: coes_mailhog
    restart: unless-stopped
    ports:
      - "8026:8025"   # UI web
      - "1026:1025"   # SMTP
  web:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.dev
    command: make run-dev
    volumes:
      - .:/app/coes
      - ./media:/app/coes/media
    environment:
      ENV: develop
      DOCKER: "1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

  celery:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.dev
    container_name: coes_celery
    restart: unless-stopped
    command: make celery
    environment:
      DOCKER: "1"
      ENV: develop
    env_file:
      - .env
    volumes:
      - .:/app/coes
      - ./media:/app/coes/media
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.dev
    container_name: coes_celery_beat
    command: make celery-beat
    restart: unless-stopped
    environment:
      DOCKER: "1"
      ENV: develop
    env_file:
      - .env
    volumes:
      - .:/app/coes
      - ./media:/app/coes/media
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  flower:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.dev
    container_name: coes_flower
    command: make celery-flower
    ports:
      - "5555:5555"
    environment:
      DOCKER: "1"
      ENV: develop
    env_file:
      - .env
    volumes:
      - .:/app/coes
    depends_on:
      web:
        condition: service_started
      redis:
        condition: service_healthy
      celery:
        condition: service_started