[pytest]
DJANGO_SETTINGS_MODULE = cfg.settings.testing
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Test
python_functions = test_*

# Output
addopts =
    -v
    --tb=short
    --durations=5
    --showlocals
    -p no:warnings
    --strict-markers

# Test discovery
testpaths = apps

# Custom markers
markers =
    slow: marks tests as slow
    integration: marks tests as integration tests
    unit: marks tests as unit tests