# Generated by Django 5.2 on 2026-06-18 02:36

import apps.security.models.users
import apps.security.utils.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('first_name', models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_text_only', message='Only upper letters, and underscores are allowed.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='First name')),
                ('last_name', models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_text_only', message='Only upper letters, and underscores are allowed.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Last name')),
                ('document_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10), apps.security.utils.validators.django_id_validator], verbose_name='Document number')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'person',
                'ordering': ['last_name', '-created_at'],
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['document_number'], name='person_documen_1aa8ae_idx'), models.Index(fields=['last_name', 'first_name'], name='person_last_na_85a3c4_idx')],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Username')),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('force_password', models.BooleanField(default=False, verbose_name='Force password change')),
                ('last_password_change', models.DateField(default=django.utils.timezone.now, verbose_name='Last password change')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Enabled'), (2, 'Disabled'), (3, 'Locked')], default=1, verbose_name='Status')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Failed login attempts')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Locked at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='security.person')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['-created_at'],
                'permissions': (('view_users', 'Can view users list'),),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('token', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='Token')),
                ('token_type', models.PositiveSmallIntegerField(choices=[(1, 'Email verification'), (2, 'Password reset')], verbose_name='Token type')),
                ('expires_at', models.DateTimeField(default=apps.security.models.users.get_default_expiration, verbose_name='Expires at')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Used'), (3, 'Expired')], default=1, verbose_name='Status')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User token',
                'verbose_name_plural': 'User tokens',
                'db_table': 'user_token',
                'ordering': ['-created_at'],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token'], name='user_token_token_deff65_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user', 'token_type'], name='user_token_user_id_5bc7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['expires_at'], name='user_token_expires_de5645_idx'),
        ),
    ]
