# Generated by Django 5.2 on 2026-06-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
