"""Django settings for coes project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config

from cfg.settings.database import DATABASES_CONFIG

# ------------------------------------------------------------------------------
# BASE PATHS
# ------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR.parent / "media"
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "staticfiles"
STATICFILES_DIRS = [BASE_DIR.parent / "static"]
LOCALE_PATHS = [BASE_DIR.parent / "locale"]

# ------------------------------------------------------------------------------
# DOMAIN & GLOBAL
# ------------------------------------------------------------------------------
APPEND_SLASH = True
DEFAULT_CHARSET = "utf-8"
DOMAIN = config("DOMAIN", default="0.0.0.0") + ":" + config("PORT", default="8000")

# ------------------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------------------
BASE_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

THIRD_APPS = [
    "auditlog",
    "crispy_forms",
    "crispy_bootstrap5",
    "widget_tweaks",
    "django_celery_beat",
    "rest_framework",
]

LOCAL_APPS = [
    "apps.catalogs",
    "apps.core",
    "apps.inventory",
    "apps.purchasing",
    "apps.security",
]

INSTALLED_APPS = BASE_APPS + THIRD_APPS + LOCAL_APPS

# ------------------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------------------
BASE_MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

THIRD_MIDDLEWARE = [
    "crum.CurrentRequestUserMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

LOCAL_MIDDLEWARE = [
    "apps.security.middleware.force_password_middleware.ForcePasswordChangeMiddleware",
]

MIDDLEWARE = BASE_MIDDLEWARE + LOCAL_MIDDLEWARE + THIRD_MIDDLEWARE

# ------------------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------------------
DB_ENGINE_SELECTED = config("DB_ENGINE", default="sqlite").lower()
DATABASES = {"default": DATABASES_CONFIG.get(DB_ENGINE_SELECTED, DATABASES_CONFIG["sqlite"])}

# ------------------------------------------------------------------------------
# TEMPLATES & URLS
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": [
                "django.templatetags.static",
                "django.templatetags.i18n",
                "django.contrib.humanize.templatetags.humanize",
            ],
            "libraries": {},
        },
    },
]

ROOT_URLCONF = "cfg.urls"
WSGI_APPLICATION = "cfg.wsgi.application"
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
# ------------------------------------------------------------------------------
# USER & AUTH
# ------------------------------------------------------------------------------
AUTH_USER_MODEL = "security.User"
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = LOGIN_URL

# ------------------------------------------------------------------------------
# SESSIONS
# ------------------------------------------------------------------------------
SESSION_COOKIE_NAME = "coes_session_id"
SESSION_COOKIE_AGE = 1800  # 30 min
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ------------------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Guayaquil"
USE_I18N = True
USE_TZ = True

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
