# Generated by Django 5.2 on 2026-06-20 16:23

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('code', models.SlugField(help_text='Unique identifier code, only lower case, numbers and underscores', unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(3)], verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Description')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Priority level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalogs',
                'db_table': 'catalog',
                'ordering': ['-created_at', 'priority'],
                'permissions': (('view_catalogs', 'Can view catalog list'),),
                'indexes': [models.Index(fields=['code'], name='catalog_code_45b3ab_idx'), models.Index(fields=['is_active'], name='catalog_is_acti_b19c09_idx')],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('code', models.SlugField(help_text='Unique identifier code, only lower case, numbers and underscores', validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(3)], verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Description')),
                ('priority', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Priority')),
                ('extra', models.CharField(blank=True, help_text="Auxiliary value, e.g. abbreviation 'ml' for 'Milliliter'", max_length=100, null=True, verbose_name='Extra value')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogs.catalog', verbose_name='Catalog')),
            ],
            options={
                'verbose_name': 'catalog item',
                'verbose_name_plural': 'catalog items',
                'db_table': 'catalog_item',
                'ordering': ['-created_at', 'priority'],
                'unique_together': {('catalog', 'code')},
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
