# Generated by Django 5.2 on 2026-06-18 02:36

import apps.core.utils.helpers
import django.core.validators
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Manufacture date')),
                ('expiry_date', models.DateField(verbose_name='Expiry date')),
                ('initial_quantity', models.PositiveIntegerField(default=0, verbose_name='Initial quantity')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Current quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit cost')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Discarded'), (1, 'Active'), (2, 'Expired'), (3, 'Depleted')], default=1, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batch',
                'ordering': ['-expiry_date'],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('concept', models.CharField(max_length=255, verbose_name='Concept')),
                ('movement_type', models.PositiveSmallIntegerField(choices=[(0, 'Inbound'), (1, 'Outbound'), (2, 'Adjustment')], verbose_name='Type')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Cancelled')], default=1, verbose_name='Status')),
                ('previous_stock', models.PositiveIntegerField(default=0, editable=False, verbose_name='Previous stock')),
                ('after_stock', models.PositiveIntegerField(default=0, editable=False, verbose_name='After stock')),
                ('is_increment', models.BooleanField(editable=False, verbose_name='Increment')),
                ('unit_cost_at_movement', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Unit cost at movement')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movement',
                'ordering': ['-created_at'],
                'permissions': (('view_inventorymovements', 'Can view movements list'),),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique identifier code, numbers and underscores', max_length=50, unique=True, verbose_name='Code')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.helpers.generate_upload_path, verbose_name='Image')),
                ('stock_min', models.PositiveIntegerField(default=10, help_text='Notify me when stock reaches this level', verbose_name='Stock min')),
                ('stock_max', models.PositiveIntegerField(default=100, help_text='Maximum stock', verbose_name='Stock max')),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
                'db_table': 'supply',
                'ordering': ['-created_at'],
                'permissions': (('view_supplies', 'Can view supply list'),),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
