# Generated by Django 5.2 on 2026-06-18 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('inventory', '0001_initial'),
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='operations.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='inventory_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='operations.inventoryorder'),
        ),
        migrations.AddField(
            model_name='supply',
            name='category',
            field=models.ForeignKey(limit_choices_to={'catalog__code': 'CAT_SUPPLY'}, on_delete=django.db.models.deletion.PROTECT, related_name='supplies_by_category', to='catalogs.catalogitem', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='supply',
            name='unit_of_measure',
            field=models.ForeignKey(limit_choices_to={'catalog__code': 'UNI_MEASURE'}, on_delete=django.db.models.deletion.PROTECT, related_name='supplies_by_unit', to='catalogs.catalogitem', verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.supply', verbose_name='Supply'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['batch', '-created_at'], name='inventory_m_batch_i_8d4aed_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'status'], name='inventory_m_movemen_4777ee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['inventory_order'], name='inventory_m_invento_5cc233_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['code'], name='supply_code_2d3d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['name'], name='supply_name_c67e26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('supply', 'batch_number')},
        ),
    ]
