# Generated by Django 5.2 on 2026-06-18 02:36

import datetime
import django.core.validators
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('order_type', models.PositiveSmallIntegerField(choices=[(0, 'Inbound'), (1, 'Outbound'), (2, 'Replenishment')], db_index=True, verbose_name='Order type')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order number')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Sent'), (2, 'Completed'), (3, 'Cancelled')], default=0, verbose_name='Status')),
                ('motive', models.TextField(max_length=500, verbose_name='Motive')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('scheduled_date', models.DateField(default=datetime.date(2026, 6, 17), help_text='The date the items are expected to arrive.', verbose_name='Schedule date')),
                ('received_date', models.DateField(blank=True, help_text='The date the items were received by the supplier.', null=True, verbose_name='Received date')),
            ],
            options={
                'verbose_name': 'Inventory Order',
                'verbose_name_plural': 'Inventory Orders',
                'db_table': 'inventory_order',
                'ordering': ['-created_at'],
                'permissions': (('view_inbound_orders', 'Can view inbound order list'), ('view_outbound_orders', 'Can view outbound order list'), ('view_replenishment_orders', 'Can view replenishment order list')),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('is_active', models.BooleanField(default=True, help_text='Check this box to enable the feature in the system.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('quantity_requested', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity requested')),
                ('quantity_fulfilled', models.PositiveIntegerField(default=0, help_text='Received (inbound) or dispatched (outbound/replenishment)', verbose_name='Quantity fulfilled')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit cost')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Order detail',
                'verbose_name_plural': 'Order details',
                'db_table': 'order_detail',
                'ordering': ['inventory_order', '-created_at'],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
