# Generated by Django 5.2 on 2026-06-20 16:23

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('operations', '0001_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.person')),
                ('business_name', models.CharField(max_length=200, verbose_name='Business name')),
                ('delivery_days', models.PositiveIntegerField(default=0, verbose_name='Delivery days')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
                'ordering': ('business_name',),
                'permissions': (('view_suppliers', 'Can view suppliers list'),),
            },
            bases=('security.person',),
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Inbound Order',
                'verbose_name_plural': 'Inbound Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operations.inventoryorder',),
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Outbound Order',
                'verbose_name_plural': 'Outbound Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operations.inventoryorder',),
        ),
        migrations.CreateModel(
            name='ReplenishmentOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Replenishment Order',
                'verbose_name_plural': 'Replenishment Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operations.inventoryorder',),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='inventory.batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='inventory_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='operations.inventoryorder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='inventory.supply', verbose_name='Supply'),
        ),
        migrations.AddField(
            model_name='inventoryorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='operations.supplier', verbose_name='Supplier'),
        ),
        migrations.AddConstraint(
            model_name='orderdetail',
            constraint=models.UniqueConstraint(fields=('inventory_order', 'supply', 'batch'), name='unique_order_supply_batch'),
        ),
        migrations.AddIndex(
            model_name='inventoryorder',
            index=models.Index(fields=['order_type', 'status'], name='inventory_o_order_t_5fc301_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryorder',
            index=models.Index(fields=['order_number'], name='inventory_o_order_n_95a735_idx'),
        ),
    ]
