# Generated by Django 5.2 on 2026-06-18 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='scheduled_date',
            field=models.DateField(default=datetime.date(2026, 6, 18), help_text='The date the items are expected to arrive.', verbose_name='Schedule date'),
        ),
    ]
