# Generated by Django 5.2 on 2026-06-18 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_inventoryorder_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='scheduled_date',
            field=models.DateField(default=datetime.date.today, help_text='The date the items are expected to arrive.', verbose_name='Schedule date'),
        ),
    ]
